// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ru.urvanov.employeelist.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import ru.urvanov.employeelist.domain.EmployeePosition;
import ru.urvanov.employeelist.domain.EmployeePositionDataOnDemand;

privileged aspect EmployeePositionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EmployeePositionDataOnDemand: @Component;
    
    private Random EmployeePositionDataOnDemand.rnd = new SecureRandom();
    
    private List<EmployeePosition> EmployeePositionDataOnDemand.data;
    
    public EmployeePosition EmployeePositionDataOnDemand.getNewTransientEmployeePosition(int index) {
        EmployeePosition obj = new EmployeePosition();
        setDescr(obj, index);
        return obj;
    }
    
    public void EmployeePositionDataOnDemand.setDescr(EmployeePosition obj, int index) {
        String descr = "descr_" + index;
        if (descr.length() > 100) {
            descr = descr.substring(0, 100);
        }
        obj.setDescr(descr);
    }
    
    public EmployeePosition EmployeePositionDataOnDemand.getSpecificEmployeePosition(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        EmployeePosition obj = data.get(index);
        Long id = obj.getId();
        return EmployeePosition.findEmployeePosition(id);
    }
    
    public EmployeePosition EmployeePositionDataOnDemand.getRandomEmployeePosition() {
        init();
        EmployeePosition obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return EmployeePosition.findEmployeePosition(id);
    }
    
    public boolean EmployeePositionDataOnDemand.modifyEmployeePosition(EmployeePosition obj) {
        return false;
    }
    
    public void EmployeePositionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = EmployeePosition.findEmployeePositionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'EmployeePosition' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<EmployeePosition>();
        for (int i = 0; i < 10; i++) {
            EmployeePosition obj = getNewTransientEmployeePosition(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
