// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ru.urvanov.employeelist.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import ru.urvanov.employeelist.domain.EmployeePosition;
import ru.urvanov.employeelist.domain.EmployeePositionDataOnDemand;
import ru.urvanov.employeelist.domain.EmployeePositionIntegrationTest;

privileged aspect EmployeePositionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EmployeePositionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EmployeePositionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EmployeePositionIntegrationTest: @Transactional;
    
    @Autowired
    EmployeePositionDataOnDemand EmployeePositionIntegrationTest.dod;
    
    @Test
    public void EmployeePositionIntegrationTest.testCountEmployeePositions() {
        Assert.assertNotNull("Data on demand for 'EmployeePosition' failed to initialize correctly", dod.getRandomEmployeePosition());
        long count = EmployeePosition.countEmployeePositions();
        Assert.assertTrue("Counter for 'EmployeePosition' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EmployeePositionIntegrationTest.testFindEmployeePosition() {
        EmployeePosition obj = dod.getRandomEmployeePosition();
        Assert.assertNotNull("Data on demand for 'EmployeePosition' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EmployeePosition' failed to provide an identifier", id);
        obj = EmployeePosition.findEmployeePosition(id);
        Assert.assertNotNull("Find method for 'EmployeePosition' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'EmployeePosition' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void EmployeePositionIntegrationTest.testFindAllEmployeePositions() {
        Assert.assertNotNull("Data on demand for 'EmployeePosition' failed to initialize correctly", dod.getRandomEmployeePosition());
        long count = EmployeePosition.countEmployeePositions();
        Assert.assertTrue("Too expensive to perform a find all test for 'EmployeePosition', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<EmployeePosition> result = EmployeePosition.findAllEmployeePositions();
        Assert.assertNotNull("Find all method for 'EmployeePosition' illegally returned null", result);
        Assert.assertTrue("Find all method for 'EmployeePosition' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EmployeePositionIntegrationTest.testFindEmployeePositionEntries() {
        Assert.assertNotNull("Data on demand for 'EmployeePosition' failed to initialize correctly", dod.getRandomEmployeePosition());
        long count = EmployeePosition.countEmployeePositions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<EmployeePosition> result = EmployeePosition.findEmployeePositionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'EmployeePosition' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'EmployeePosition' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EmployeePositionIntegrationTest.testFlush() {
        EmployeePosition obj = dod.getRandomEmployeePosition();
        Assert.assertNotNull("Data on demand for 'EmployeePosition' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EmployeePosition' failed to provide an identifier", id);
        obj = EmployeePosition.findEmployeePosition(id);
        Assert.assertNotNull("Find method for 'EmployeePosition' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEmployeePosition(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'EmployeePosition' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EmployeePositionIntegrationTest.testMergeUpdate() {
        EmployeePosition obj = dod.getRandomEmployeePosition();
        Assert.assertNotNull("Data on demand for 'EmployeePosition' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EmployeePosition' failed to provide an identifier", id);
        obj = EmployeePosition.findEmployeePosition(id);
        boolean modified =  dod.modifyEmployeePosition(obj);
        Integer currentVersion = obj.getVersion();
        EmployeePosition merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'EmployeePosition' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EmployeePositionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'EmployeePosition' failed to initialize correctly", dod.getRandomEmployeePosition());
        EmployeePosition obj = dod.getNewTransientEmployeePosition(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'EmployeePosition' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'EmployeePosition' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'EmployeePosition' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void EmployeePositionIntegrationTest.testRemove() {
        EmployeePosition obj = dod.getRandomEmployeePosition();
        Assert.assertNotNull("Data on demand for 'EmployeePosition' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'EmployeePosition' failed to provide an identifier", id);
        obj = EmployeePosition.findEmployeePosition(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'EmployeePosition' with identifier '" + id + "'", EmployeePosition.findEmployeePosition(id));
    }
    
}
