// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ru.urvanov.employeelist.domain;

import org.springframework.beans.factory.annotation.Configurable;
import ru.urvanov.employeelist.domain.EmployeeIntegrationTest;

privileged aspect EmployeeIntegrationTest_Roo_Configurable {
    
    declare @type: EmployeeIntegrationTest: @Configurable;
    
}
