// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ru.urvanov.employeelist.domain;

import ru.urvanov.employeelist.domain.Department;

privileged aspect Department_Roo_JavaBean{

public String Department.getDescr(){return this.descr;}

public void Department.setDescr(String descr){this.descr=descr;}

}
